import { Chatbox } from "@/components/chatbox";
import { Footer } from "@/components/footer";
import { Header } from "@/components/header";
import { Toaster } from "@/components/ui/sonner";
import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ro" className={`${geist.variable}`} suppressHydrationWarning>
      <body suppressHydrationWarning>
        <div className="flex min-h-svh flex-col">
          <Header />
          <div className="grow">{children}</div>
          <Footer />
        </div>
        <Chatbox />
        <Toaster />
      </body>
    </html>
  );
}
